### ISSUE TITLE
communeKey to canton

### ISSUE THREAD

**Issue by marinkobabic** [openpotato/openplzapi#1]
As first well done 👏  Looking at the current API there is no way to get from communeKey to the specific canton without going through all the cantons and doing lookup there for the specific communeKey. 

when returning localities
```
[
  {
    "source": "string",
    "timeStamp": "2022-12-27",
    "key": "10023770",
    "locality": {
      "source": "string",
      "timeStamp": "2022-12-27",
      "communeKey": "string",
      "name": "Grellingen",
      "postalCode": "4203"
    },
    "name": "Wiedenweg",
    "status": "None"
  }
]
```
It may make sense to return also the the of the canton key and name. To not have a bad impact to the performance, this information needs to be persisted accordantly.

An alternate approach would be to create an extra endpoint therefore, which does not exist as of today.

Congratulations to this first feature request 😄

**Comment by fstueber** [comment]
You are right, from communeKey to Canton is a long way. The API is not fixed yet. There will soon be an update to to improve this. Thanks a lot for your feedback.

**Comment by fstueber** [comment]
Please have a look at the new version of OpenPLZ API. API surface has changed and should give back now much better information. Any feedback is welcome.
