### ISSUE TITLE
Paging funktioniert nicht mehr

### ISSUE THREAD

**Issue by eOPUS-Alex** [openpotato/openplzapi#4]
**Beschreibung:**
Mir ist aufgefallen, dass seit kurzem das Paging nicht mehr korrekt funktioniert. 

**Schritte zur Reproduktion:**
Sende eine Anfrage an die folgende URL: 
`https://openplzapi.org/de/Streets?postalCode=32052&locality=Herford&page=1&pageSize=50`

**Erwartetes Ergebnis:**
Es sollten nur die ersten 50 Einträge der Straßen zurückgegeben werden.

**Tatsächliches Ergebnis:**
Es werden alle 245 Einträge zurückgegeben, anstatt nur der ersten 50.

**Schritte zur Reproduktion:**
Sende eine Anfrage an: 
`https://openplzapi.org/de/Streets?postalCode=32052&locality=Herford&page=2&pageSize=50`

**Erwartetes Ergebnis:**
Es sollten nur die nächsten 50 Einträge (ab Eintrag 51) angezeigt werden.

**Tatsächliches Ergebnis:**
Wieder werden alle 245 Einträge zurückgegeben, anstatt nur die entsprechenden 50 der zweiten Seite.

_Vielen Dank für den großartigen Service und die kontinuierliche Weiterentwicklung von OpenPLZAPI!_

**Comment by fstueber** [comment]
Korrigiert. Danke für die Rückmeldung.

**Comment by eOPUS-Alex** [comment]
Vielen Dank für die schnelle Lösung des Problems
